python YX.py --index 0 --clean 0 --threads 32 --hide 0
REM python YX.py --index 1 --clean 1 --threads 32 --hide 0
REM python YX.py --index 2 --clean 1 --threads 32 --hide 0
REM python YX.py --index 3 --clean 1 --threads 32 --hide 0
REM python YX.py --index 4 --clean 1 --threads 32 --hide 0
REM python YX.py --index 5 --clean 1 --threads 32 --hide 0
REM python YX.py --index 6 --clean 1 --threads 32 --hide 0
REM python YX.py --index 7 --clean 1 --threads 32 --hide 0
REM python YX.py --index 8 --clean 1 --threads 32 --hide 0
REM python YX.py --index 9 --clean 1 --threads 32 --hide 0
REM python YX.py --index 10 --clean 1 --threads 32 --hide 0
REM python YX.py --index 12 --clean 1 --threads 32 --hide 0
REM python YX.py --index 13 --clean 1 --threads 32 --hide 0
REM python YX.py --index 14 --clean 1 --threads 32 --hide 0
REM python YX.py --index 15 --clean 1 --threads 32 --hide 0
REM python YX.py --index 16 --clean 1 --threads 32 --hide 0
REM python YX.py --index 17 --clean 1 --threads 32 --hide 0
REM python YX.py --index 18 --clean 1 --threads 32 --hide 0
REM python YX.py --index 19 --clean 1 --threads 32 --hide 0